config/routes.rb
Rails.application.routes.draw do
  root to: 'tanks#index'
  devise_for :users, :controllers => { registrations: 'registrations', :omniauth_callbacks => "users/omniauth_callbacks" }
  resources :fish, only: [:index]

  resources :tanks, only: [] do
    resources :fish, only: [:new, :create, :update, :destroy, :edit]
    resources :plants, only: [:new, :create, :update, :destroy, :edit]
  end
  resources :users, only: [:show] do
    resources :tanks, only: [:new, :create, :show, :update, :destroy, :edit]
    resources :maintenances, only: [:new, :index, :create, :update, :destroy, :edit]
    resources :tasks, only: [:index, :edit, :update, :destroy]

  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/tank.rb
class Tank < ApplicationRecord
  belongs_to :user
  has_many :fish
  has_many :plants
  has_many :maintenances
  has_many :tanks, through: :maintenances

  validates_presence_of :name
  validates_uniqueness_of :name
  validates :size, numericality: { greater_than: 0 }

  def self.recent
    order(created_at: :desc).limit(5)
  end
end

app/controllers/tanks_controller.rb
class TanksController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index]
  before_action :redirect_if_not_authorized, only: [:edit, :update, :destroy]
  def index
    @tanks = Tank.all
  end

  def show
    @tank = Tank.find(params[:id])
  end

  def new
    @tank = Tank.new
  end

  def create
    @tank = Tank.new(tank_params)
    if @tank.save
      redirect_to user_tank_path(current_user, @tank)
    else
      render :new
    end

  end

  def edit
    if params[:user_id]
      user = User.find_by(id: params[:user_id])
      if user.nil?
        redirect_to user_tank_path, alert: "User not found."
      else
        @tank = user.tanks.find_by(id: params[:id])
        redirect_to user_tanks_path(user), alert: "Tank not found." if @tank.nil?
      end
    else
      @tank = Tank.find(params[:id])
    end
  end

  def update
    @tank = Tank.find(params[:id])
    if @tank.update(tank_params)
      redirect_to user_tank_path(@tank)
    else
      render 'edit'
    end
  end

  def destroy
    @tank = Tank.find(params[:id])
    @user = User.find(@tank.user_id)
    @tank.fish.each do |f|
      f.destroy
    end
    @tank.plants.each do |p|
      p.destroy
    end
    @tank.maintenances.each do |m|
      m.destroy
    end
    @tank.destroy
    redirect_to user_path(@user)
  end

  private

  def redirect_if_not_authorized
    redirect_to '/' unless current_user == Tank.find(params[:id]).user
  end

  def tank_params
    params.require(:tank).permit(:name, :size, :description, :image, :user_id)
  end
end

app/helpers/tanks_helper.rb
module TanksHelper
end

app/views/tanks/_errors.html.erb
<% if @tank.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@tank.errors.count, "error") %>
      prohibited this tank from being saved:
    </h2>

    <ul>
      <% @tank.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/tanks/_form.html.erb
<%= form_for( [:user, @tank] ) do |f| %>
  <%= f.hidden_field :user_id, value: current_user.id %>
  <p><%= f.label :name %>
    <%= f.text_field :name %></p>
  <p><%= f.label :size, "Size (gallons)" %>
    <%= f.number_field :size %><br></p>
  <p><%= f.label :description %><br>
    <%= f.text_area :description %></p>
  <p><%= f.label :image, "Image URL" %>
    <%= f.text_field :image %></p>
  <%= f.submit %>
<% end %>

app/views/tanks/edit.html.erb
<h1>Update <%= @tank.name %></h1>
<%= render 'errors' %>
<%= render 'form' %>
<br>
<%= button_to "Delete Tank", user_tank_path(current_user, @tank), method: :delete %>

app/views/tanks/index.html.erb
<h1>TankMate</h1>
<p>Track and maintain your aquariums with ease!</p>
<p><%= link_to 'Search for owners by fish!', fish_index_path %></p>
<h2>Recent Additions</h2>
<ul>
<% @tanks.recent.each do |t| %>
  <li>
    Owner: <%= t.user.name %><br>
    Tank: <%= link_to t.name, user_tank_path(t.user, t) %> - <%= t.size %> gallons<br>
    <% unless t.image.blank? %>
      <img src="<%= t.image %>" alt="<%= t.name.capitalize %>" height="100"><br>
    <% end %>
    <%= t.description %><br><br>
  </li>
<% end %>
</ul>

app/views/tanks/new.html.erb
<h1>Create New Tank</h1>
<%= render 'errors' %>
<%= render 'form' %>

app/views/tanks/show.html.erb
<h1><%= @tank.name.upcase %></h1>

<h2>Size: <%= @tank.size %> gallons</h2>

<% if !@tank.image.blank? %>
  <img src="<%= @tank.image %>" alt="<%= @tank.name.capitalize %> Image" height="300">
<% else %>
  No Image Uploaded
<% end %>

<h3>Description:</h3>
<p><%= @tank.description %></p>

<% if @tank.user == current_user %>
  <%= button_to "Update Tank Details", edit_user_tank_path, method: :get %>
<% end %>

<h3>Stock List:</h3>
<div>
  <h4>Fish:</h4>
  <%= render @tank.fish %>
  <% if @tank.user == current_user %>
    <br>
    <%= button_to "Add Fish", new_tank_fish_path(@tank), method: :get %>
  <% end %>
</div>

<div>
  <h4>Plants:</h4>
  <%= render @tank.plants %>
  <% if @tank.user == current_user %>
    <br>
    <%= button_to "Add Plants", new_tank_plant_path(@tank), method: :get %>
  <% end %>
</div>
<% if @tank.user != current_user %>
  <br>
  <%= button_to "#{@tank.user.name}'s Tanks", user_path(@tank.user_id), method: :get %>
<% end %>