config/routes.rb
Rails.application.routes.draw do
  root to: 'tanks#index'
  devise_for :users, :controllers => { registrations: 'registrations', :omniauth_callbacks => "users/omniauth_callbacks" }
  resources :fish, only: [:index]

  resources :tanks, only: [] do
    resources :fish, only: [:new, :create, :update, :destroy, :edit]
    resources :plants, only: [:new, :create, :update, :destroy, :edit]
  end
  resources :users, only: [:show] do
    resources :tanks, only: [:new, :create, :show, :update, :destroy, :edit]
    resources :maintenances, only: [:new, :index, :create, :update, :destroy, :edit]
    resources :tasks, only: [:index, :edit, :update, :destroy]

  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  has_many :tanks
  has_many :maintenances, through: :tanks
  has_many :tasks, through: :maintenances

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  devise :omniauthable, :omniauth_providers => [:facebook]

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.first_name = auth.info.first_name
      user.last_name = auth.info.last_name
      user.username = auth.info.name
      user.password = Devise.friendly_token[0,20]
    end
  end

  def name
    "#{first_name} #{last_name}"
  end

  def gallons
    gallons = 0
    tanks.each do |t|
      gallons += t.size
    end
    gallons
  end

  def fish_count
    fish_count = 0
    tanks.each do |t|
      fish_count += t.fish.count
    end
    fish_count
  end

  def plants_count
    plants_count = 0
    tanks.each do |t|
      plants_count += t.plants.count
    end
    plants_count
  end

  def completed_tasks_count
    completed_tasks = 0
    maintenances.each do |m|
      completed_tasks += 1 if m.complete
    end
    completed_tasks
  end

  def incomplete_tasks_count
    incomplete_tasks = 0
    maintenances.each do |m|
      incomplete_tasks += 1 unless m.complete
    end
    incomplete_tasks
  end


end

app/controllers/users/maintenances_controller.rb
class MaintenancesController < ApplicationController
  def index
    @maintenances = Maintenance.all
  end

  def show
    @maintenance = Maintenance.find(params[:id])
  end

  def new
    @maintenance = Maintenance.new
  end

  def create
    @maintenance = Maintenance.new(maintenance_params)
    if @maintenance.save
      redirect_to user_maintenances_path(current_user)
    else
      render :new
    end

  end

  def edit

  end

  def update

  end

  def destroy
    @maintenance = Maintenance.find(params[:id])
    @maintenance.destroy
    redirect_to user_maintenances_path(current_user)
  end

  private

  def maintenance_params
    params.require(:maintenance).permit(:due, :complete?, :notes, :tank_id, :task_id)
  end

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    @user = User.from_omniauth(request.env["omniauth.auth"])
    sign_in_and_redirect @user
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/show.html.erb
<h1><%= @user.name %></h1>
<% if @user == current_user %>
  <%= button_to "Edit User", edit_user_registration_path(@user), method: :get %>
<% end %>
<div>
  <h2>Stats</h2>
  <p>Total tanks: <%= @user.tanks.count %></p>
  <p>Total gallons: <%= @user.gallons %></p>
  <p>Total fish: <%= @user.fish_count %></p>
  <p>Total plants: <%= @user.plants_count %></p>
  <p>Completed Tasks: <%= @user.completed_tasks_count %></p>
  <p>Incomplete Tasks: <%= @user.incomplete_tasks_count %></p>
</div>

<div>
  <h2>Tanks</h2>
  <% @user.tanks.each do |t| %>
    <p><%= link_to t.name, user_tank_path(@user, t) %> - <%= t.size %> gallons<br>
    <% unless t.image.blank? %>
      <img src="<%= t.image %>" alt="<%= t.name.capitalize %>" height="100"><br>
      <% end %></p>
  <% end %>

  <% if @user == current_user %>
    <%= button_to "Create Tank", new_user_tank_path(@user), method: :get %>
  <% end %>
</div>

<div>
  <h2>Upcoming Maintenance</h2>
  <ul>
    <% @user.maintenances.this_week.order(:due).each do |m| %>
      <li><%= m.due.strftime("%A, %b %e") %> - <%= m.tank.name %> - <%= m.task.title %></li>
    <% end %>
  </ul>
  <%= button_to "View All Scheduled Maintenance", user_maintenances_path(@user), method: :get %>
</div>