config/routes.rb
Rails.application.routes.draw do
  root to: 'tanks#index'
  devise_for :users, :controllers => { registrations: 'registrations', :omniauth_callbacks => "users/omniauth_callbacks" }
  resources :fish, only: [:index]

  resources :tanks, only: [] do
    resources :fish, only: [:new, :create, :update, :destroy, :edit]
    resources :plants, only: [:new, :create, :update, :destroy, :edit]
  end
  resources :users, only: [:show] do
    resources :tanks, only: [:new, :create, :show, :update, :destroy, :edit]
    resources :maintenances, only: [:new, :index, :create, :update, :destroy, :edit]
    resources :tasks, only: [:index, :edit, :update, :destroy]

  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/maintenance.rb
class Maintenance < ApplicationRecord
  belongs_to :task
  belongs_to :tank
  accepts_nested_attributes_for :task

  validates :due, presence: true
  validate :due_cannot_be_in_the_past

  def initialize(params)
    super(params)
    set_task(params) if params
  end

  def set_task(maintenance_params)
    if maintenance_params[:task_id].blank?
      t = Task.find_or_create_by(title: maintenance_params[:task_attributes][:title].capitalize)

    else
      t = Task.find(maintenance_params[:task_id])
    end
    self.task = t
  end

  def due_cannot_be_in_the_past
    if due.present? && due < Date.today
      errors.add(:due, "date can't be in the past")
    end
  end

  def status
    complete ? "Complete" : "Incomplete"
  end

  def self.by_tank(tank)
    where(tank: tank)
  end

  def self.by_task(task)
    where(task: task)
  end

  # scope :active, -> { where state: 'active' }
  scope :today, -> { where 'due =?', Date.today }

  # def self.today
  #   where('due =?', Date.today)
  # end

  def self.upcoming
    where('due >?', Date.today)
  end

  def self.overdue
    where('due <?', Date.today)
  end

  def self.by_complete
    where(complete: true)
  end

  def self.by_incomplete
    where(complete: false)
  end

  def self.this_week
    where('due >=?', Date.today) && where('due <=?', (Date.today + 7))
  end


end

app/controllers/maintenances_controller.rb
class MaintenancesController < ApplicationController
  before_action :redirect_if_not_authorized, only: [:edit, :update, :destroy]
  helper_method :params
  def index
    @user = User.find(params[:user_id])
    @maintenances = @user.maintenances

    if !params[:tank].blank?
      @maintenances = Maintenance.by_tank(params[:tank])
    elsif !params[:task].blank?
      @maintenances = Maintenance.by_task(params[:task])
    elsif !params[:due].blank?
      @maintenances = if params[:due] == 'Today'
                        Maintenance.today
                      elsif params[:due] == 'Upcoming'
                        Maintenance.upcoming
                      else
                        Maintenance.overdue
                      end
    elsif !params[:status].blank?
      @maintenances = if params[:status] == 'Complete'
                        Maintenance.by_complete
                      else
                        Maintenance.by_incomplete
                      end
    end
  end

  def new
    @maintenance = Maintenance.new
  end

  def create
    if maintenance_params[:tank_id].length == 1
      @maintenance = Maintenance.new(maintenance_params)
      @maintenance.save
      render :new and return
    else
      maintenance_params[:tank_id].each do |t|
        unless t.blank?
          @maintenance = Maintenance.new(maintenance_params)
          @maintenance.tank_id = t
          render :new and return unless @maintenance.save
        end
      end
    end
    redirect_to user_maintenances_path(current_user)
  end

  def edit
    @maintenance = Maintenance.find(params[:id])
  end

  def update
    @maintenance = Maintenance.find(params[:id])
    if @maintenance.update(maintenance_params)
      redirect_to user_maintenances_path(current_user)
    else
      render 'edit'
    end
  end

  def destroy
    @maintenance = Maintenance.find(params[:id])
    @maintenance.destroy
    redirect_to user_maintenances_path(current_user)
  end

  private

  def redirect_if_not_authorized
    unless current_user.id.to_s == params[:user_id]
      redirect_to user_maintenances_path(params[:user_id])
    end
  end

  def maintenance_params
    params.require(:maintenance).permit(
        :due,
        :complete,
        :notes,
        :task_id,
        tank_id: [],
        :task_attributes => :title
      )
  end



end

app/controllers/users/maintenances_controller.rb
class MaintenancesController < ApplicationController
  def index
    @maintenances = Maintenance.all
  end

  def show
    @maintenance = Maintenance.find(params[:id])
  end

  def new
    @maintenance = Maintenance.new
  end

  def create
    @maintenance = Maintenance.new(maintenance_params)
    if @maintenance.save
      redirect_to user_maintenances_path(current_user)
    else
      render :new
    end

  end

  def edit

  end

  def update

  end

  def destroy
    @maintenance = Maintenance.find(params[:id])
    @maintenance.destroy
    redirect_to user_maintenances_path(current_user)
  end

  private

  def maintenance_params
    params.require(:maintenance).permit(:due, :complete?, :notes, :tank_id, :task_id)
  end

end

app/views/maintenances/_errors.html.erb
<% if @maintenance.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@maintenance.errors.count, "error") %>
      prohibited this maintenance from being scheduled:
    </h2>

    <ul>
      <% @maintenance.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/maintenances/_form.html.erb
<%= form_for([current_user, @maintenance]) do |f| %>
  <div>
    <p><%= f.label :due, "Due Date:" %>
    <%= f.date_select :due %></p>

    <p><%= f.label :complete, 'Complete:' %>
    <%= f.check_box :complete %></p>
  </div>

  <% if @maintenance.new_record? %>
  <!--  Select tanks from list-->
    <fieldset>
      <legend>Tanks</legend>
      <%= f.collection_check_boxes :tank_id, current_user.tanks.each, :id, :name %>
    </fieldset>

  <!--  Select or create tasks -->
    <fieldset>
      <legend>Tasks</legend>
      <%= f.collection_select :task_id, Task.all, :id, :title, {include_blank: 'Create New Task'} %>
      <%= f.fields_for :task, Task.new do |t| %>
        <%= t.text_field :title %>
      <% end %>
    </fieldset>
  <% end %>

  <p><%= f.label :notes %>:<br>
  <%= f.text_area :notes %></p>

  <%= f.submit %>
<% end %>

app/views/maintenances/edit.html.erb
<h1>Update <%= @maintenance.tank.name %> Maintenance</h1>
<h2>Task: <%= @maintenance.task.title %></h2>
<%= render 'errors' %>
<%= render 'form' %>
<%= button_to "Delete Scheduled Maintenance", user_maintenance_path, method: :delete %>

app/views/maintenances/index.html.erb


<h1><%= link_to "#{@user.name}'s", user_path(@user) %> Tank Maintenance Log</h1>
<% if @user == current_user %>
  <%= button_to "Schedule Maintenance", new_user_maintenance_path(@user), method: :get %>
<% end %>
<br>
<div>
  <table>
    <tr>
      <th>Status</th>
      <th>Date</th>
      <th>Task</th>
      <th>Tank</th>
    </tr>
    <tr>
      <%= form_tag("/users/#{@user.id}/maintenances", method: 'get') do %>
        <td><%= select_tag 'status', options_for_select(['Complete', 'Incomplete']), include_blank: "Filter by Status" %></td>
        <td><%= select_tag 'due', options_for_select(['Today', 'Upcoming', 'Overdue']), include_blank: "Filter by Date" %></td>
        <td><%= select_tag 'task', options_from_collection_for_select(@user.tasks.uniq, 'id', 'title'), include_blank: "Filter by Task" %></td>
        <td><%= select_tag 'tank', options_from_collection_for_select(@user.tanks, 'id', 'name'), include_blank: "Filter by Tank" %></td>
        <td><%= submit_tag 'Filter' %></td>
      <% end %>

    </tr>
    <% @maintenances.order(:due).each do |m| %>
      <tr>
        <td><%= m.status %></td>
        <td><%= m.due %></td>
        <td><%= m.task.title %></td>
        <td><%= link_to m.tank.name, user_tank_path(@user, m.tank) %></td>
        <% if @user == current_user %>
          <td><%= link_to "Update", edit_user_maintenance_path(@user, m), method: :get %></td>
        <% end %>
      </tr>
    <% if m.complete %>
      <tr>
        <td></td>
        <td valign="top">Notes:</td>
        <td colspan="4"><%= m.notes %></td></tr>
      <% end %>
    <% end %>
  </table>
</div>

app/views/maintenances/new.html.erb
<h1>Schedule Maintenance</h1>
<%= render 'errors' %>
<%= render 'form' %>