config/routes.rb
Rails.application.routes.draw do
  root to: 'tanks#index'
  devise_for :users, :controllers => { registrations: 'registrations', :omniauth_callbacks => "users/omniauth_callbacks" }
  resources :fish, only: [:index]

  resources :tanks, only: [] do
    resources :fish, only: [:new, :create, :update, :destroy, :edit]
    resources :plants, only: [:new, :create, :update, :destroy, :edit]
  end
  resources :users, only: [:show] do
    resources :tanks, only: [:new, :create, :show, :update, :destroy, :edit]
    resources :maintenances, only: [:new, :index, :create, :update, :destroy, :edit]
    resources :tasks, only: [:index, :edit, :update, :destroy]

  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/fish.rb
class Fish < ApplicationRecord
  belongs_to :tank
  validates_presence_of :species
  validates :quantity, numericality: { greater_than_or_equal_to: 0 }
end

app/controllers/fish_controller.rb
class FishController < ApplicationController
  before_action :redirect_if_not_authorized, only: [:edit, :update, :destroy]
  def new
    @fish = Fish.new(tank_id: params[:tank_id])
  end

  def index
    if params[:search] && !params[:search].blank?
      @fishes = Fish.where("species like ?", "%#{params[:search].titleize}%")
      if @fishes.empty?
        flash[:notice] = "Fish not found"
        @fishes = Fish.all
        render :index
      end
    else
      @fishes = Fish.all
    end
  end

  def create
    @fish = Fish.new(fish_params)
    if @fish.save
      redirect_to user_tank_path(current_user, fish_params[:tank_id])
    else
      render :new
    end
  end

  def update
    @fish = Fish.find(params[:id])
    if @fish.update(fish_params)
      redirect_to user_tank_path(current_user, fish_params[:tank_id])
    else
      render 'edit'
    end
  end

  def edit
    @fish = Fish.find(params[:id])
  end

  def destroy
    @fish = Fish.find(params[:id])
    tank = Tank.find(@fish.tank_id)
    @fish.destroy
    redirect_to user_tank_path(current_user, tank)
  end

  private

  def redirect_if_not_authorized
    unless current_user == Fish.find(params[:id]).tank.user
      redirect_to user_tank_path(Tank.find(params[:tank_id]).user, params[:tank_id])
    end
  end

  def fish_params
    params.require(:fish).permit(:species, :image, :quantity, :tank_id)
  end
end

app/helpers/fish_helper.rb
module FishHelper

  def owners_list(fish)
    list = fish.collect do |f|
      f.tank.user
    end
    list.uniq
  end

  def tank_list(owner, fish)
    list = []
    fish.each do |f|
      if f.tank.user_id == owner.id
        list << f.tank
      end
    end
    list.uniq
  end


end

app/views/fish/_errors.html.erb
<% if @fish.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@fish.errors.count, "error") %>
      prohibited this action from being saved:
    </h2>

    <ul>
      <% @fish.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/fish/_fish.html.erb
<%= fish.quantity %> <%= fish.species.pluralize(fish.quantity) %> - <img src="<%= fish.image %>" alt="<%= fish.species.capitalize %>" height="50"><br>
<% if @tank.user == current_user %>
  <%= button_to "Update Stock", edit_tank_fish_path(@tank, fish), method: :get %>
<% end %>

app/views/fish/_form.html.erb
<%= form_for( [:tank, @fish] ) do |f| %>
  <%= f.hidden_field :tank_id %>
  <p><%= f.label :species %>
    <%= f.text_field :species %></p>
  <p><%= f.label :quantity %>
    <%= f.number_field :quantity %><br></p>
  <p><%= f.label :image, "Image URL" %>
    <%= f.text_field :image %></p>
  <%= f.submit %>
<% end %>

app/views/fish/edit.html.erb
<h1>Edit Fish</h1>
<%= render 'errors' %>
<%= render 'form' %>
<%= button_to "Delete Fish", tank_fish_path, method: :delete %>

app/views/fish/index.html.erb
<% if @fishes == Fish.all %>
  <h1>Fish Owners List</h1>
  <% else %>
  <h1><%= @fishes.first.species %> Owners List</h1>
<% end %>
<%= form_tag("/fish", method: 'get') do %>
  <%= label_tag 'search', 'Search For Fish:' %>
  <%= text_field_tag 'search' %>
  <%= submit_tag 'Search' %>
<% end %>

<ul>
  <% owners = owners_list(@fishes) %>
  <% owners.each do |owner| %>
    <li><%=link_to owner.name, user_path(owner.id) %>
      <% tanks = tank_list(owner, @fishes) %>
      <ol>
        <% tanks.each do |tank| %>
        <li><%= link_to tank.name, user_tank_path(tank.user_id, tank) %></li>
        <% end %>
      </ol>
  </li>
  <% end %>
</ul>

app/views/fish/new.html.erb
<h1>Add Fish</h1>
<%= render 'errors' %>
<%= render 'form' %>